import { readFileSync } from "fs";
import { join } from "path";
import { NextRequest, NextResponse } from "next/server";

// Fonts we host locally (generated by scripts/generate-glyphs.mjs)
const LOCAL_FONTS = new Set(["TID UI Regular", "TID UI Bold"]);
const FONTS_DIR = join(process.cwd(), "public/fonts");

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ params: string[] }> }
) {
  const { params: segments } = await params;
  // segments = ["TID UI Regular", "0-255.pbf"]
  const range = segments.pop()!;                   // "0-255.pbf"
  const fontstack = segments.join("/");             // "TID UI Regular"
  const rangeBase = range.replace(/\.pbf$/, "");   // "0-255"

  if (LOCAL_FONTS.has(fontstack)) {
    // Serve from public/fonts/
    try {
      const filePath = join(FONTS_DIR, fontstack, `${rangeBase}.pbf`);
      const buf = readFileSync(filePath);
      return new NextResponse(buf, {
        headers: {
          "Content-Type": "application/x-protobuf",
          "Cache-Control": "public, max-age=86400",
        },
      });
    } catch {
      return new NextResponse("Not found", { status: 404 });
    }
  }

  // Proxy to CartoDB for all other fonts (Noto Sans, Roboto, etc.)
  const upstream = `https://tiles.basemaps.cartocdn.com/fonts/${encodeURIComponent(fontstack)}/${range}`;
  const res = await fetch(upstream);
  if (!res.ok) return new NextResponse("Upstream error", { status: res.status });
  const buf = await res.arrayBuffer();
  return new NextResponse(buf, {
    headers: {
      "Content-Type": "application/x-protobuf",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
